Rework `gardenadm` kustomizations (move to `/dev-setup`) (#12331)
* Move `gardenadm` high-touch machine config to `/dev-setup/gardenadm/machines`

* Nit: Simplify import path

* Move `{.skaffold-image,.imagevector-overwrite.yaml}` to `/dev-setup/gardenadm`

In a later commit, they will actually be moved to `/dev-setup/gardenadm/resources`.

* Move `resources` to `/dev-setup/gardenadm/resources`

It doesn't fit perfectly there since it is not a typical Kustomize
component/part, but it doesn't make sense to move it elsewhere, so let's
live with it.

* Also move `{.skaffold-image,.imagevector-overwrite.yaml}` to `/dev-setup/gardenadm/resources`

Since this `resources` folder is no typical Kustomize part anyways,
let's also move the other files there so that they are at one place.

* Prefactor: ControllerRegistration component for networking extensions

`/dev-setup/extensions/networking-{calico,cilium}` now have the same
structure like `/dev-setup/extensions/provider-local`

* Prefactor: Use cloud provider secret from `/dev-setup/gardenconfig`

* Move resources to `/dev-setup-gardenadm/resources`

* Move generated resources to `/dev-setup/gardenadm/resources/generated`

Otherwise, `gardenadm` might complain if we put the generated files into
the same directory that also contains the `kustomzation.yaml`:

```
Error: failed reading Kubernetes resources from config directory ./dev-setup/gardenadm/resources/medium-touch: failed reading Kubernetes resources from config directory: failed decoding resource at index 0 in kustomization.yaml: no kind "Kustomization" is registered for version "kustomize.config.k8s.io/v1beta1" in scheme "pkg/runtime/scheme.go:110"
exit status 1
```

* Address PR review feedback