Fix `make kind-up IPFAMILY=dual`
Without this fix, it fails to apply the calico kustomization:

```
error: trouble configuring builtin PatchTransformer with config: `
path: ../ipv4/patch-calico-default-ippool.yaml
`: failed to get the patch file from path(../ipv4/patch-calico-default-ippool.yaml): security; file '/root/go/src/github.com/gardener/gardener/example/gardener-local/calico/ipv4/patch-calico-default-ippool.yaml' is not in or below '/root/go/src/github.com/gardener/gardener/example/gardener-local/calico/dual'
make: *** [Makefile:300: kind-up] Error 1
```

Probably this is broken since some time, but nobody noticed. :)
On the way, I already moved the calico kustomization to the new
structure in `/dev-setup/kind/calico`.