Fix `logcheck` plugin compilation
Fix build issues when `logcheck` is used for Gardener extensions.

```
Error: build linters: unable to load custom analyzer "logcheck": hack/tools/bin/darwin-arm64/logcheck.so, plugin.Open("/go/src/github.com/gardener/gardener-extension/hack/tools/bin/darwin-arm64/logcheck"): plugin was built with a different version of package golang.org/x/tools/go/analysis
Failed executing command with error: build linters: unable to load custom analyzer "logcheck": hack/tools/bin/darwin-arm64/logcheck.so, plugin.Open("/go/src/github.com/gardener/gardener-extension/hack/tools/bin/darwin-arm64/logcheck"): plugin was built with a different version of package golang.org/x/tools/go/analysis
make: *** [check] Error 3
```

Co-authored-by: Plamen Kokanov <plamen.kokanov@sap.com>