[extensions] Improvement for webhook/certificate management library (#13765)
* Support skipping component name prefixing

Previously, if the component name was not beginning with `gardener-`, we
have implicitly prefixed it with `gardener-extension-`.

However, there are usages of this library for non-native Gardener
extensions. Hence, let's support that this prefix is not added
automatically if desired.

* Certificate reconciler creates webhook configs if not present

Previously, it was only patching the CA if the webhook config was not
present.
This required custom code to initially create the webhook config (like
in `gardener-operator`), with special care to prevent races.

Now, the certificate reconciler creates the webhook config if not found.

* Support shoot webhooks without `ManagedResource`

Typically, Gardener extensions manage their webhooks in shoot via
a `ManagedResource`.

However, if this code is used by a component responsible for the garden
cluster, a "shoot webhook" is a "virtual cluster webhook". In such
cases, direct management (w/o a `ManagedResource`) can be beneficial,
especially if the component does not have RBAC/a kubeconfig for the
runtime cluster.

Hence, let's support this by checking if
`ShootWebhookManagedResourceName` is set. If not, we just treat the
shoot webhooks like "source webhooks" and manage them directly.

* Retry seed webhook config reconciliation

Now that the certificate reconciler directly creates the webhook config
if it does not exist, this can race with this function (which is
executed in parallel to the reconciler on `manager.Manager` start).

Example integration test failure:

```
• [FAILED] [0.780 seconds]
Certificates tests run with seed webhook seed webhook does not yet exist [It] should create the webhook and inject the CA bundle
/go/src/github.com/gardener/gardener/test/integration/extensions/webhook/certificates/certificates_test.go:484

  Timeline >>
  STEP: Create test Namespaces @ 01/11/26 23:46:19.485
  {"level":"info","ts":"2026-01-11T23:46:19.487+0100","logger":"extensions-webhook-certificates-test","msg":"Created extension Namespace for test","namespaceName":"webhook-certs-test-jhn6w"}
  {"level":"info","ts":"2026-01-11T23:46:19.488+0100","logger":"extensions-webhook-certificates-test","msg":"Created shoot Namespace for test","namespaceName":"shoot--foo--bms8l"}
  STEP: Setup manager @ 01/11/26 23:46:19.488
  STEP: Register webhooks @ 01/11/26 23:46:19.488
  {"level":"info","ts":"2026-01-11T23:46:19.488+0100","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/seed-path"}
  {"level":"info","ts":"2026-01-11T23:46:19.488+0100","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/shoot-mutation-path"}
  {"level":"info","ts":"2026-01-11T23:46:19.488+0100","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/shoot-validating-path"}
  {"level":"info","ts":"2026-01-11T23:46:19.575+0100","logger":"secretsmanager","msg":"Generated new secret","configName":"ca-provider-test-2b16f58d-webhook","secret":{"name":"ca-provider-test-2b16f58d-webhook-e6522b26","namespace":"webhook-certs-test-jhn6w"}}
  {"level":"info","ts":"2026-01-11T23:46:19.579+0100","logger":"secretsmanager","msg":"Generated new secret","configName":"ca-provider-test-2b16f58d-webhook-bundle","secret":{"name":"ca-provider-test-2b16f58d-webhook-bundle-ad47b4a1","namespace":"webhook-certs-test-jhn6w"}}
  {"level":"info","ts":"2026-01-11T23:46:20.014+0100","logger":"secretsmanager","msg":"Generated new secret","configName":"provider-test-2b16f58d-webhook-server","secret":{"name":"provider-test-2b16f58d-webhook-server-2588fd7c","namespace":"webhook-certs-test-jhn6w"}}
  STEP: Verify certificates exist on disk @ 01/11/26 23:46:20.018
  STEP: Start manager @ 01/11/26 23:46:20.03
  {"level":"info","ts":"2026-01-11T23:46:20.030+0100","logger":"controller-runtime.webhook","msg":"Starting webhook server"}
  {"level":"info","ts":"2026-01-11T23:46:20.030+0100","msg":"Starting EventSource","controller":"webhook-certificate-reloader","source":"func source: 0x10663f6e0"}
  {"level":"info","ts":"2026-01-11T23:46:20.030+0100","msg":"Starting Controller","controller":"webhook-certificate-reloader"}
  {"level":"info","ts":"2026-01-11T23:46:20.030+0100","msg":"Starting workers","controller":"webhook-certificate-reloader","worker count":1}
  {"level":"info","ts":"2026-01-11T23:46:20.030+0100","msg":"Starting EventSource","controller":"webhook-certificate","source":"func source: 0x10663f6e0"}
  {"level":"info","ts":"2026-01-11T23:46:20.030+0100","msg":"Starting Controller","controller":"webhook-certificate"}
  {"level":"info","ts":"2026-01-11T23:46:20.030+0100","msg":"Starting workers","controller":"webhook-certificate","worker count":1}
  {"level":"debug","ts":"2026-01-11T23:46:20.030+0100","msg":"Checking for updated webhook server certificate in secret","controller":"webhook-certificate-reloader","object":{"name":""},"namespace":"","name":"","reconcileID":"faef20d3-1533-481a-b205-3d5f5970fb64","secretConfigName":"provider-test-2b16f58d-webhook-server","secretNamespace":"webhook-certs-test-jhn6w","identity":"gardener-extension-provider-test-2b16f58d-webhook","certDir":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs"}
  {"level":"info","ts":"2026-01-11T23:46:20.031+0100","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate","cert":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.crt","key":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.key"}
  {"level":"info","ts":"2026-01-11T23:46:20.031+0100","logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
  {"level":"info","ts":"2026-01-11T23:46:20.031+0100","logger":"controller-runtime.certwatcher","msg":"Starting certificate poll+watcher","cert":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.crt","key":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.key","interval":"10s"}
  {"level":"info","ts":"2026-01-11T23:46:20.131+0100","msg":"Found new secret, writing certificate to disk","controller":"webhook-certificate-reloader","object":{"name":""},"namespace":"","name":"","reconcileID":"faef20d3-1533-481a-b205-3d5f5970fb64","secretConfigName":"provider-test-2b16f58d-webhook-server","secretNamespace":"webhook-certs-test-jhn6w","identity":"gardener-extension-provider-test-2b16f58d-webhook","certDir":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs","secretName":"provider-test-2b16f58d-webhook-server-2588fd7c"}
  {"level":"debug","ts":"2026-01-11T23:46:20.132+0100","logger":"controller-runtime.certwatcher","msg":"certificate event","cert":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.crt","key":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.key","event":"CHMOD         \"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.key\""}
  {"level":"info","ts":"2026-01-11T23:46:20.132+0100","msg":"Generated webhook CA","controller":"webhook-certificate","object":{"name":""},"namespace":"","name":"","reconcileID":"5f206390-b914-4c81-861c-a337ea0d389e","secretNamespace":"webhook-certs-test-jhn6w","identity":"gardener-extension-provider-test-2b16f58d-webhook","caSecretName":"ca-provider-test-2b16f58d-webhook-e6522b26","caBundleSecretName":"ca-provider-test-2b16f58d-webhook-bundle-ad47b4a1"}
  {"level":"info","ts":"2026-01-11T23:46:20.133+0100","msg":"Generated webhook server cert","controller":"webhook-certificate","object":{"name":""},"namespace":"","name":"","reconcileID":"5f206390-b914-4c81-861c-a337ea0d389e","secretNamespace":"webhook-certs-test-jhn6w","identity":"gardener-extension-provider-test-2b16f58d-webhook","caSecretName":"ca-provider-test-2b16f58d-webhook-e6522b26","caBundleSecretName":"ca-provider-test-2b16f58d-webhook-bundle-ad47b4a1","serverSecretName":"provider-test-2b16f58d-webhook-server-2588fd7c"}
  {"level":"debug","ts":"2026-01-11T23:46:20.140+0100","logger":"controller-runtime.certwatcher","msg":"certificate event","cert":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.crt","key":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.key","event":"WRITE         \"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.key\""}
  {"level":"debug","ts":"2026-01-11T23:46:20.192+0100","logger":"controller-runtime.certwatcher","msg":"certificate event","cert":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.crt","key":"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.key","event":"WRITE|CHMOD   \"/var/folders/_s/25b7cr1s0xx31t47k1v7xm7r0000gn/T/k8s-webhook-server/serving-certs/tls.crt\""}
  {"level":"info","ts":"2026-01-11T23:46:20.240+0100","msg":"Updated source webhook config with new CA bundle","controller":"webhook-certificate","object":{"name":""},"namespace":"","name":"","reconcileID":"5f206390-b914-4c81-861c-a337ea0d389e","secretNamespace":"webhook-certs-test-jhn6w","identity":"gardener-extension-provider-test-2b16f58d-webhook","caSecretName":"ca-provider-test-2b16f58d-webhook-e6522b26","caBundleSecretName":"ca-provider-test-2b16f58d-webhook-bundle-ad47b4a1","webhookConfig":{"name":"gardener-extension-provider-test-2b16f58d"}}
  {"level":"info","ts":"2026-01-11T23:46:20.243+0100","msg":"Stopping and waiting for non leader election runnables"}
  {"level":"info","ts":"2026-01-11T23:46:20.243+0100","msg":"Stopping and waiting for warmup runnables"}
  {"level":"info","ts":"2026-01-11T23:46:20.243+0100","msg":"Shutdown signal received, waiting for all workers to finish","controller":"webhook-certificate-reloader"}
  {"level":"info","ts":"2026-01-11T23:46:20.243+0100","msg":"All workers finished","controller":"webhook-certificate-reloader"}
  {"level":"info","ts":"2026-01-11T23:46:20.243+0100","msg":"Stopping and waiting for leader election runnables"}
  {"level":"info","ts":"2026-01-11T23:46:20.243+0100","msg":"Shutdown signal received, waiting for all workers to finish","controller":"webhook-certificate"}
  {"level":"error","ts":"2026-01-11T23:46:20.244+0100","msg":"Reconciler error","controller":"webhook-certificate","object":{"name":""},"namespace":"","name":"","reconcileID":"5f206390-b914-4c81-861c-a337ea0d389e","error":"error reconciling all shoot webhook configs: 1 error occurred:\n\t* Timeout: failed waiting for *v1.PartialObjectMetadata Informer to sync\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:474\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:421\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.22.4/pkg/internal/controller/controller.go:296"}
  {"level":"info","ts":"2026-01-11T23:46:20.244+0100","msg":"All workers finished","controller":"webhook-certificate"}
  {"level":"info","ts":"2026-01-11T23:46:20.244+0100","msg":"Stopping and waiting for caches"}
  {"level":"error","ts":"2026-01-11T23:46:20.244+0100","logger":"controller-runtime.cache.UnhandledError","msg":"Failed to watch","reflector":"pkg/mod/k8s.io/client-go@v0.34.3/tools/cache/reflector.go:290","type":"*v1.PartialObjectMetadata","error":"Get \"https://127.0.0.1:53477/apis/resources.gardener.cloud/v1alpha1/managedresources?allowWatchBookmarks=true&resourceVersion=233&timeout=8m22s&timeoutSeconds=502&watch=true\": context canceled","stacktrace":"k8s.io/apimachinery/pkg/util/runtime.logError\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/runtime/runtime.go:221\nk8s.io/apimachinery/pkg/util/runtime.handleError\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/runtime/runtime.go:212\nk8s.io/apimachinery/pkg/util/runtime.HandleErrorWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/runtime/runtime.go:198\nk8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\t/go/pkg/mod/k8s.io/client-go@v0.34.3/tools/cache/reflector.go:205\nk8s.io/client-go/tools/cache.(*Reflector).RunWithContext.func1\n\t/go/pkg/mod/k8s.io/client-go@v0.34.3/tools/cache/reflector.go:361\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/wait/backoff.go:233\nk8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/wait/backoff.go:255\nk8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/wait/backoff.go:256\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/wait/backoff.go:233\nk8s.io/client-go/tools/cache.(*Reflector).RunWithContext\n\t/go/pkg/mod/k8s.io/client-go@v0.34.3/tools/cache/reflector.go:359\nk8s.io/client-go/tools/cache.(*controller).RunWithContext.(*Group).StartWithContext.func3\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/wait/wait.go:63\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.34.3/pkg/util/wait/wait.go:72"}
  {"level":"info","ts":"2026-01-11T23:46:20.244+0100","msg":"Stopping and waiting for webhooks"}
  {"level":"info","ts":"2026-01-11T23:46:20.244+0100","logger":"controller-runtime.webhook","msg":"Shutting down webhook server with timeout of 1 minute"}
  STEP: Verify CA bundle was written in atomic shoot webhook configs @ 01/11/26 23:46:20.25
  {"level":"info","ts":"2026-01-11T23:46:20.253+0100","msg":"Stopping and waiting for HTTP servers"}
  {"level":"info","ts":"2026-01-11T23:46:20.253+0100","msg":"Wait completed, proceeding to shutdown the manager"}
  [FAILED] in [It] - /go/src/github.com/gardener/gardener/test/integration/extensions/webhook/certificates/certificates_test.go:453 @ 01/11/26 23:46:20.254
  STEP: Delete webhook config @ 01/11/26 23:46:20.254
  STEP: Stop manager @ 01/11/26 23:46:20.256
  STEP: Delete shoot namespace @ 01/11/26 23:46:20.256
  STEP: Finalize shoot namespace and wait until it's gone @ 01/11/26 23:46:20.259
  STEP: Delete extension namespace @ 01/11/26 23:46:20.264
  << Timeline

  [FAILED] Expected success, but got an error:
      <*fmt.wrapError | 0x14000833b60>:
      error reconciling seed webhook config: error reconciling seed webhook config: mutatingwebhookconfigurations.admissionregistration.k8s.io "gardener-extension-provider-test-2b16f58d" already exists
      {
          msg: "error reconciling seed webhook config: error reconciling seed webhook config: mutatingwebhookconfigurations.admissionregistration.k8s.io \"gardener-extension-provider-test-2b16f58d\" already exists",
          err: <*fmt.wrapError | 0x14000833b40>{
              msg: "error reconciling seed webhook config: mutatingwebhookconfigurations.admissionregistration.k8s.io \"gardener-extension-provider-test-2b16f58d\" already exists",
              err: <*errors.StatusError | 0x14000827040>{
                  ErrStatus: {
                      TypeMeta: {Kind: "", APIVersion: ""},
                      ListMeta: {
                          SelfLink: "",
                          ResourceVersion: "",
                          Continue: "",
                          RemainingItemCount: nil,
                      },
                      Status: "Failure",
                      Message: "mutatingwebhookconfigurations.admissionregistration.k8s.io \"gardener-extension-provider-test-2b16f58d\" already exists",
                      Reason: "AlreadyExists",
                      Details: {
                          Name: "gardener-extension-provider-test-2b16f58d",
                          Group: "admissionregistration.k8s.io",
                          Kind: "mutatingwebhookconfigurations",
                          UID: "",
                          Causes: nil,
                          RetryAfterSeconds: 0,
                      },
                      Code: 409,
                  },
              },
          },
      }
  In [It] at: /go/src/github.com/gardener/gardener/test/integration/extensions/webhook/certificates/certificates_test.go:453 @ 01/11/26 23:46:20.254
------------------------------
•

Summarizing 1 Failure:
  [FAIL] Certificates tests run with seed webhook seed webhook does not yet exist [It] should create the webhook and inject the CA bundle
  /go/src/github.com/gardener/gardener/test/integration/extensions/webhook/certificates/certificates_test.go:453

Ran 3 of 3 Specs in 10.171 seconds
FAIL! -- 2 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestCertificates (10.17s)
FAIL
FAIL	github.com/gardener/gardener/test/integration/extensions/webhook/certificates	11.092s
FAIL
```

* Revert "Support shoot webhooks without `ManagedResource`"

This reverts commit be917e2cb3fdded6d4cd1e08b50439314a48810c.

Ref: https://github.com/gardener/gardener/pull/13765#discussion_r2681977455