Add gardenctl-v2
gardenctl-v2 is installed and configured to allow to practise using
this tool in the local setup.

Note that gardenctl target seed ... does not work in the gardener HA setup,

  # g target seed local-ha-multi-zone
  Error: failed to get kubeconfig for seed /local-ha-multi-zone:
  failed to get secret garden/local-ha-multi-zone.login:
  secrets "local-ha-multi-zone.login" not found

because indeed this secret is not available in the virtual garden cluster.

g target shoot local works as expected