Copy applier options to prevent overriding them globally
Also, we observed panics due to concurrent map writes:

```
fatal error: concurrent map read and map write

goroutine 630 [running]:
runtime.throw(0x1a3d1e6, 0x21)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00258a480 sp=0xc00258a450 pc=0x42c782
runtime.mapaccess2(0x17d15e0, 0xc000412a50, 0xc00258a510, 0xc00954fb3a, 0x2)
        /usr/local/go/src/runtime/map.go:472 +0x284 fp=0xc00258a4c8 sp=0xc00258a480 pc=0x40d564
github.com/gardener/gardener/pkg/client/kubernetes.(*Applier).mergeObjects(0xc00b7dc7c0, 0xc018c9d380, 0xc018c9d388, 0xc000412a50, 0x7, 0xc00720f0f0)
        /go/src/github.com/gardener/gardener/pkg/client/kubernetes/apply.go:149 +0x252 fp=0xc00258a590 sp=0xc00258a4c8 pc=0x1272722
github.com/gardener/gardener/pkg/client/kubernetes.(*Applier).applyObject(0xc00b7dc7c0, 0x1d40b00, 0xc000048030, 0xc018c9d380, 0xc000412a50, 0x0, 0x0)
        /go/src/github.com/gardener/gardener/pkg/client/kubernetes/apply.go:98 +0x355 fp=0xc00258a690 sp=0xc00258a590 pc=0x1272325
github.com/gardener/gardener/pkg/client/kubernetes.(*Applier).ApplyManifest(0xc00b7dc7c0, 0x1d40b00, 0xc000048030, 0x1cfae00, 0xc01140c600, 0xc000412a50, 0xe, 0x0)
        /go/src/github.com/gardener/gardener/pkg/client/kubernetes/apply.go:172 +0x92 fp=0xc00258a6f0 sp=0xc00258a690 pc=0x1272862
github.com/gardener/gardener/pkg/client/kubernetes.(*chartApplier).ApplyChartWithOptions(0xc00b7dc7e0, 0x1d40b00, 0xc000048030, 0xc0198bab40, 0x15, 0x1a1b5fe, 0x6, 0x1a23c49, 0xe, 0x0, ...)
        /go/src/github.com/gardener/gardener/pkg/client/kubernetes/chartapplier.go:73 +0x112 fp=0xc00258a768 sp=0xc00258a6f0 pc=0x1272d92
github.com/gardener/gardener/pkg/operation/seed.BootstrapCluster(0xc004b10180, 0xc000a6f6e0, 0xc00078ac00, 0x35, 0x40, 0x46, 0x80, 0x0)
        /go/src/github.com/gardener/gardener/pkg/operation/seed/seed.go:385 +0x25b1 fp=0xc00258b360 sp=0xc00258a768 pc=0x1393051
github.com/gardener/gardener/pkg/controllermanager/controller/seed.(*defaultControl).ReconcileSeed(0xc000098d20, 0xc010002600, 0xc009d29c8c, 0x3, 0x0, 0x0)
        /go/src/github.com/gardener/gardener/pkg/controllermanager/controller/seed/seed_control.go:276 +0x14f9 fp=0xc00258bc80 sp=0xc00258b360 pc=0x156ebd9
github.com/gardener/gardener/pkg/controllermanager/controller/seed.(*Controller).reconcileSeedKey(0xc00098db00, 0xc002fd0cbc, 0x3, 0x18, 0xc0054d3d68)
        /go/src/github.com/gardener/gardener/pkg/controllermanager/controller/seed/seed_control.go:92 +0x224 fp=0xc00258bd28 sp=0xc00258bc80 pc=0x156d514
github.com/gardener/gardener/pkg/controllermanager/controller/seed.(*Controller).reconcileSeedKey-fm(0xc002fd0cbc, 0x3, 0xc00112ea80, 0x1776540)
        /go/src/github.com/gardener/gardener/pkg/controllermanager/controller/seed/seed_control.go:76 +0x3e fp=0xc00258bd60 sp=0xc00258bd28 pc=0x157038e
github.com/gardener/gardener/pkg/controllermanager/controller/utils.worker.func1.1(0x1d66140, 0xc00112ea80, 0xc00233cb10, 0x1a1a094, 0x4, 0xc001067e00)
        /go/src/github.com/gardener/gardener/pkg/controllermanager/controller/utils/worker.go:53 +0xe3 fp=0xc00258be00 sp=0xc00258bd60 pc=0x1299b03
...
```