Switch local dual-stack setup to `gardener-operator` (#12986)
* Fix `make kind-up IPFAMILY=dual`

Without this fix, it fails to apply the calico kustomization:

```
error: trouble configuring builtin PatchTransformer with config: `
path: ../ipv4/patch-calico-default-ippool.yaml
`: failed to get the patch file from path(../ipv4/patch-calico-default-ippool.yaml): security; file '/root/go/src/github.com/gardener/gardener/example/gardener-local/calico/ipv4/patch-calico-default-ippool.yaml' is not in or below '/root/go/src/github.com/gardener/gardener/example/gardener-local/calico/dual'
make: *** [Makefile:300: kind-up] Error 1
```

Probably this is broken since some time, but nobody noticed. :)
On the way, I already moved the calico kustomization to the new
structure in `/dev-setup/kind/calico`.

* Also move `metrics-server` to `/dev-setup/kind`

Since we are already on it ... :)

* Expose virtual garden address in dual-stack setup

* Introduce `ipFamilies` in `Garden` API for runtime cluster

The kind cluster in the local dual-stack setup has two IP families, so
we also need to reflect this - mostly, in order to properly configure
the istio used for exposing the virtual garden -> see next commit.

Note that this "ipFamily"/dual-stack completion is not complete for the
`Garden` with this enhancement. It is just one puzzle piece to make the
local setup work. If we really want to support dual-stack runtime
clusters, we need to put some follow-up effort into this story.

* Properly configure virtual-garden istio for dual-stack

Similar to
- https://github.com/gardener/gardener/blob/80d9cdd6fa35c7014ab012ebfb53c02c7d3385ae/pkg/gardenlet/controller/seed/seed/components.go#L342
- https://github.com/gardener/gardener/blob/485c25124ea536e4610c627109017dd34d434921/pkg/gardenlet/operation/seed/seed.go#L235

* Prepare `Garden` and `provider-local` for dual-stack

- Move from `example/provider-local/garden/dual`
- Configure `Garden` for dual-stack

--> `make kind-single-node-up operator-up IPFAMILY=dual`

* Set `kube-apiserver`'s bind address to `::`

Previously, we didn't need to care about this because we never had
dual-stack seed or garden runtime clusters.
We can now simply set the bind-address to `::` to make the socket accept
both IPv6 and IPv4 traffic.

Without this, `kube-apiserver` defaults to `0.0.0.0` which doesn't work
for our dual-stack scenario.

* Drop ipv6 artefacts in kind cluster setup

IPv6/dual has now been moved to operator-based setup completely.

* Drop `seed-kind/local-ipv6` artefacts

Should have been cleaned up with
https://github.com/gardener/gardener/pull/12709

* Drop explicit `clusterIP` configuration for `gardener-admission-controller`

`gardener-operator` manages this automagically, no need for this
anymore.

* Move `Seed` spec configuration to `/dev-setup`